package com.example.chrono

/** Un texte en trois langues. */
class T3(private val fr: String, private val en: String, private val zh: String) {
    fun t(): String = when (Settings.lang) {
        Lang.FR -> fr
        Lang.EN -> en
        Lang.ZH -> zh
    }
}

/**
 * Explication d'un réglage, affichée par un appui long sur ce réglage (écran « Infos »,
 * ou au-dessus des curseurs min / max pour les curseurs). Les lignes sont séparées par « \n ».
 */
class Info(val key: String, val title: S, fr: String, en: String, zh: String) {
    private val text = T3(fr, en, zh)
    fun body(): String = text.t()

    companion object {
        val all: List<Info> = listOf(
            // ---------------- Essentiels
            Info("eco", S.ECO,
                "Économise la batterie : on n'affiche plus les dixièmes de seconde, l'écran se met à jour une fois par seconde, les couleurs deviennent noir et blanc et la luminosité est réglable.\nLes tours sont enregistrés au fil de l'eau dans un fichier.\nL'appli redémarre quand on change ce réglage.",
                "Saves battery: tenths of a second are hidden, the screen refreshes once per second, colors turn black and white and brightness becomes adjustable.\nLaps are appended to a file as you go.\nThe app restarts when you change this setting.",
                "节省电量：不显示十分之一秒，屏幕每秒刷新一次，颜色变为黑白，亮度可调。\n圈次会随时追加写入文件。\n更改此设置时应用会重新启动。"),
            Info("ecoBright", S.ECO_BRIGHT,
                "Luminosité de l'écran en mode éco, de 0 % (le minimum du système) à 100 %.\nElle repart de 0 % à chaque activation du mode éco.\nUn appui long ouvre la plage min / max du curseur.",
                "Screen brightness in eco mode, from 0 % (system minimum) to 100 %.\nIt restarts at 0 % each time eco mode is switched on.\nA long press opens the slider's min / max range.",
                "省电模式下的屏幕亮度，从 0 %（系统最低）到 100 %。\n每次开启省电模式时都会从 0 % 重新开始。\n长按可打开滑块的最小 / 最大范围。"),
            Info("hold", S.HOLD,
                "Durée pendant laquelle il faut maintenir le doigt pour valider une action protégée : Reset, effacer, supprimer une séance, cadenas, ouvrir l'explication d'un réglage…\nUn cercle de progression se remplit pendant l'appui et la montre vibre à la fin.\nPlus c'est court, plus c'est rapide, mais plus on risque une erreur.",
                "How long you must keep your finger down to confirm a protected action: Reset, clear, delete a session, padlock, open a setting's explanation…\nA progress ring fills while you hold, and the watch vibrates when done.\nShorter is faster but riskier.",
                "确认受保护操作所需的按住时间：重置、清除、删除记录、解锁、打开设置说明等。\n按住时进度环会逐渐填满，完成时手表会振动。\n时间越短越快，但也越容易误触。"),
            Info("colR", S.RED,
                "Part de rouge de la couleur de référence (0 à 255).\nCette couleur sert aux boutons Start, au cercle, aux tours et à tous les accents de l'appli.\nLes trois curseurs Rouge, Vert et Bleu se combinent.",
                "Red part of the reference color (0 to 255).\nThis color is used for the Start button, the ring, the laps and every accent of the app.\nThe Red, Green and Blue sliders combine.",
                "参考颜色中的红色成分（0 至 255）。\n该颜色用于开始按钮、圆环、圈次和应用中的所有强调色。\n红、绿、蓝三个滑块会混合成最终颜色。"),
            Info("colG", S.GREEN,
                "Part de vert de la couleur de référence (0 à 255).\nCette couleur sert aux boutons Start, au cercle, aux tours et à tous les accents de l'appli.\nLes trois curseurs Rouge, Vert et Bleu se combinent.",
                "Green part of the reference color (0 to 255).\nThis color is used for the Start button, the ring, the laps and every accent of the app.\nThe Red, Green and Blue sliders combine.",
                "参考颜色中的绿色成分（0 至 255）。\n该颜色用于开始按钮、圆环、圈次和应用中的所有强调色。\n红、绿、蓝三个滑块会混合成最终颜色。"),
            Info("colB", S.BLUE,
                "Part de bleu de la couleur de référence (0 à 255).\nCette couleur sert aux boutons Start, au cercle, aux tours et à tous les accents de l'appli.\nLes trois curseurs Rouge, Vert et Bleu se combinent.",
                "Blue part of the reference color (0 to 255).\nThis color is used for the Start button, the ring, the laps and every accent of the app.\nThe Red, Green and Blue sliders combine.",
                "参考颜色中的蓝色成分（0 至 255）。\n该颜色用于开始按钮、圆环、圈次和应用中的所有强调色。\n红、绿、蓝三个滑块会混合成最终颜色。"),
            Info("lock", S.LOCK,
                "Quand on lance le chrono, l'écran tactile est verrouillé pour éviter les appuis involontaires (poignet, manche, pluie…).\nLe bouton physique du bas continue de fonctionner.\nPour déverrouiller : maintenir le cadenas en haut de l'écran.",
                "When you start the timer, the touchscreen is locked to avoid accidental touches (wrist, sleeve, rain…).\nThe bottom physical button keeps working.\nTo unlock: hold the padlock at the top of the screen.",
                "启动秒表时会锁定触摸屏，避免误触（手腕、衣袖、雨水等）。\n底部的实体按键仍然可用。\n解锁方法：长按屏幕顶部的锁图标。"),
            Info("autoUnlock", S.AUTO_UNLOCK,
                "Déverrouille automatiquement l'écran tactile après ce délai (de « Jamais » à 24 h).\nUtile si l'on oublie de maintenir le cadenas.\nUn appui long ouvre la plage min / max du curseur.",
                "Automatically unlocks the touchscreen after this delay (from « Never » to 24 h).\nHandy if you forget to hold the padlock.\nA long press opens the slider's min / max range.",
                "超过此时间后自动解锁触摸屏（从“从不”到 24 小时）。\n忘记长按锁图标时很有用。\n长按可打开滑块的最小 / 最大范围。"),
            Info("ringInLock", S.RING_IN_LOCK,
                "Autorise la bague rotative (ou le bord tactile Samsung) à faire défiler la liste des tours même quand l'écran est verrouillé.\nLe reste du tactile reste bloqué.",
                "Lets the rotary bezel (or Samsung's touch bezel) scroll the lap list even while the screen is locked.\nThe rest of the touchscreen stays blocked.",
                "即使屏幕已锁定，也允许旋转表圈（或三星触摸表圈）滚动圈次列表。\n触摸屏的其他部分仍保持锁定。"),
            Info("aod", S.AOD,
                "Garde l'écran allumé tant que le chrono tourne, malgré le délai de veille réglé dans le système.\nAprès un moment sans toucher la montre (voir « Délai avant veille »), l'écran passe en veille douce : fond noir, chiffres gris, luminosité minimale. Un appui ou le bouton du bas le réveille.\nAttention : risque de marquage de l'écran AMOLED et batterie consommée plus vite.",
                "Keeps the screen on while the timer runs, whatever sleep delay the system uses.\nAfter a moment without touching the watch (see « Dim delay »), the screen goes into a soft dim state: black background, gray digits, minimum brightness. A touch or the bottom button wakes it.\nWarning: risk of AMOLED burn-in and faster battery drain.",
                "秒表运行期间保持屏幕常亮，不受系统息屏时间影响。\n一段时间未触碰手表后（见“息屏延迟”），屏幕进入柔和待机：黑底、灰色数字、最低亮度。触摸屏幕或按底部按键即可唤醒。\n注意：可能造成 AMOLED 烧屏，并加快耗电。"),
            Info("aodDelay", S.AOD_DELAY,
                "Temps sans toucher la montre avant que l'affichage permanent passe en veille douce (noir, chiffres gris, luminosité minimale).\nNe s'applique que pendant que le chrono tourne.\nUn appui long ouvre la plage min / max du curseur.",
                "Time without touching the watch before the always-on display switches to its soft dim state (black, gray digits, minimum brightness).\nOnly applies while the timer is running.\nA long press opens the slider's min / max range.",
                "常亮显示在多长时间未触碰手表后进入柔和待机（黑底、灰色数字、最低亮度）。\n仅在秒表运行时有效。\n长按可打开滑块的最小 / 最大范围。"),
            Info("runIcons", S.RUN_ICONS,
                "Affiche les icônes Réglages et Suivi en haut de l'écran pendant que le chrono tourne ou affiche un temps (on les ouvre alors par un appui long).\nSi l'option est désactivée, ces écrans ne sont accessibles qu'une fois le chrono remis à zéro. Un paramètre mal réglé (verrou, taille, couleur…) ne peut alors plus être corrigé pendant l'activité.",
                "Shows the Settings and Tracking icons at the top while the timer runs or shows a time (open them with a long press).\nIf disabled, those screens are only reachable once the timer is reset. A badly set parameter (lock, size, color…) can then no longer be fixed during an activity.",
                "秒表运行或显示时间时，在屏幕顶部显示设置和跟踪图标（长按打开）。\n关闭后，只有重置秒表才能进入这些界面。若某项参数设置不当（锁定、大小、颜色等），活动期间将无法修改。"),
            Info("help", S.HELP_TOGGLE,
                "Affiche l'icône « ? » en haut de l'écran quand le chrono est à zéro. Elle ouvre l'aide complète de l'application.",
                "Shows the « ? » icon at the top when the timer is at zero. It opens the app's full help.",
                "秒表归零时，在屏幕顶部显示“?”图标，点按可打开完整的应用帮助。"),
            Info("track", S.TRACK,
                "Active le suivi avancé : icône de graphique en haut de l'écran, allure par tour (distance par tour) et objectifs d'exercice / repos avec vibrations.\nLe suivi est aussi accessible pendant l'activité par un appui long sur son icône.",
                "Turns on advanced tracking: a chart icon at the top, pace per lap (distance per lap) and exercise / rest goals with vibrations.\nIt is also reachable during an activity with a long press on its icon.",
                "启用高级跟踪：屏幕顶部出现图表图标，可设置每圈配速（每圈距离）以及带振动的运动 / 休息目标。\n活动期间也可长按其图标进入。"),
            Info("custom", S.CUSTOM,
                "Affiche ou masque tous les réglages avancés (langue, logo, mise en page, colonnes, tailles, QR, vibrations…).\nLes réglages essentiels restent toujours visibles.",
                "Shows or hides all advanced settings (language, logo, layout, columns, sizes, QR, vibration…).\nEssential settings always stay visible.",
                "显示或隐藏所有高级设置（语言、图标、布局、列、大小、二维码、振动等）。\n基本设置始终可见。"),

            // ---------------- Personnalisation
            Info("lang", S.LANGUAGE,
                "Langue de l'application : français, anglais ou chinois simplifié.\nElle s'applique tout de suite, y compris à ces explications et à l'aide.",
                "App language: French, English or Simplified Chinese.\nIt applies immediately, including these explanations and the help.",
                "应用语言：法语、英语或简体中文。\n立即生效，包括这些说明和帮助。"),
            Info("logo", S.LOGO,
                "Choisit l'icône de l'appli. Elle change aussi sur le tile, la complication du cadran et la pastille « chrono en cours ».\nLe nom reste « Super StopWatch ». Sur certaines montres, le lanceur met quelques secondes à se rafraîchir.",
                "Chooses the app icon. It also changes on the tile, the watch-face complication and the « timer running » chip.\nThe name stays « Super StopWatch ». On some watches the launcher takes a few seconds to refresh.",
                "选择应用图标。磁贴、表盘复杂功能和“秒表运行中”提示也会同步更换。\n名称始终为“Super StopWatch”。部分手表的启动器需要几秒钟才会刷新。"),
            Info("light", S.LIGHT,
                "Inverse les gris : fond blanc, texte noir. Pratique en plein soleil.\nAllume beaucoup de pixels : risque de marquage de l'écran AMOLED et batterie consommée bien plus vite.",
                "Inverts the grays: white background, black text. Handy in bright sunlight.\nLights up many pixels: risk of AMOLED burn-in and much faster battery drain.",
                "反转灰度：白底黑字，适合强光下使用。\n会点亮大量像素：可能造成 AMOLED 烧屏，并大幅增加耗电。"),
            Info("ring", S.RING,
                "Affiche le cercle autour de l'écran : une lumière (le « snake ») fait le tour du cadran.\nUn tour de cercle = 1 minute au départ, puis la durée du meilleur tour. En suivi avancé avec un objectif, il suit le segment en cours.\nDésactivé automatiquement en mode éco.",
                "Shows the ring around the screen: a light (the « snake ») travels around the dial.\nOne revolution = 1 minute at first, then your best lap time. In advanced tracking with a goal, it follows the current segment.\nAutomatically off in eco mode.",
                "显示屏幕周围的圆环：一道光（“光带”）绕表盘运行。\n一圈 = 起初 1 分钟，之后为最佳圈速。启用高级跟踪并设置目标时，则对应当前阶段。\n省电模式下自动关闭。"),
            Info("snake", S.SNAKE,
                "Longueur du snake, en % de la circonférence du cercle.\nUn petit snake est plus précis, un grand snake est plus lisible de loin.\nUn appui long ouvre la plage min / max du curseur.",
                "Length of the snake, in % of the ring's circumference.\nA short snake is more precise, a long one is easier to read from afar.\nA long press opens the slider's min / max range.",
                "光带长度，占圆环周长的百分比。\n短光带更精确，长光带更容易远看。\n长按可打开滑块的最小 / 最大范围。"),
            Info("autoScroll", S.AUTO_SCROLL,
                "Quand on est tout en haut de la liste, un nouveau tour reste visible en haut.\nSi on est plus bas, la vue ne bouge pas pour ne pas faire perdre sa place.",
                "When you are at the very top of the list, a new lap stays visible at the top.\nIf you are further down, the view does not move so you keep your place.",
                "位于列表最顶部时，新的圈次会保持在顶部可见。\n若已向下滚动，视图不会移动，以免丢失当前位置。"),
            Info("lefty", S.LEFTY,
                "Inverse l'ordre des cercles : Start passe à gauche, Tour / Reset à droite.\nPratique si la montre est portée au poignet droit.",
                "Reverses the order of the circles: Start moves to the left, Lap / Reset to the right.\nHandy if the watch is worn on the right wrist.",
                "反转圆形按钮的顺序：开始移到左边，计圈 / 重置移到右边。\n手表戴在右手腕时很方便。"),
            Info("undo", S.UNDO_BTN,
                "Ajoute un troisième cercle « Annuler » qui retire le dernier tour enregistré (le chrono continue).\nLes trois cercles sont alors un peu plus petits.",
                "Adds a third « Undo » circle that removes the last recorded lap (the timer keeps running).\nThe three circles are then slightly smaller.",
                "增加第三个“撤销”圆形按钮，可删除最近记录的一圈（秒表继续运行）。\n此时三个圆形按钮会略小一些。"),
            Info("sec", S.SECONDS,
                "Affiche le temps en secondes seulement (par exemple 125 au lieu de 02:05), plus gros et plus lisible.\nLes dixièmes restent affichés hors mode éco.",
                "Shows time in seconds only (for example 125 instead of 02:05), larger and easier to read.\nTenths are still shown outside eco mode.",
                "只以秒显示时间（例如 125，而不是 02:05），字体更大更易读。\n非省电模式下仍显示十分之一秒。"),
            Info("fade", S.FADE,
                "Estompe progressivement le haut et le bas de la liste des tours, pour un rendu plus doux sur l'écran rond.",
                "Gradually fades the top and bottom of the lap list for a softer look on the round screen.",
                "让圈次列表的顶部和底部逐渐淡出，在圆形屏幕上显得更柔和。"),
            Info("markers", S.MARKERS,
                "Affiche un petit triangle devant chaque tour : ▲ = plus rapide que la référence, ▼ = plus lent. Aucun triangle si le temps est identique ou s'il n'y a pas de référence.\nLa référence est le tour précédent. En suivi avancé, avec un objectif d'exercice réglé, c'est le tour de même rang dans la série précédente (une série = le nombre de répétitions).",
                "Shows a small triangle before each lap: ▲ = faster than the reference, ▼ = slower. No triangle when the time is identical or there is no reference.\nThe reference is the previous lap. In advanced tracking with an exercise goal set, it is the lap of the same rank in the previous series (a series = the number of repetitions).",
                "在每一圈前显示小三角：▲ = 比参照更快，▼ = 更慢。时间相同或没有参照时不显示。\n参照为上一圈。启用高级跟踪并设置运动目标时，参照为上一组中相同序号的一圈（一组 = 重复次数）。"),
            Info("colNum", S.COL_NUM,
                "Colonne du numéro de tour. Au moins une des quatre colonnes de base (N°, Total, Tour, Écart) reste toujours affichée.",
                "Lap number column. At least one of the four base columns (No., Total, Lap, Delta) always stays visible.",
                "圈次序号列。四个基本列（序号、总计、单圈、差值）中至少保留一列。"),
            Info("colTotal", S.COL_TOTAL,
                "Colonne du temps total écoulé depuis le départ, au moment de chaque tour.",
                "Column with the total time elapsed since the start, at the moment of each lap.",
                "显示每一圈结束时自启动以来的总用时。"),
            Info("colLap", S.COL_LAP,
                "Colonne de la durée de chaque tour (depuis le tour précédent), colorée du meilleur au pire.",
                "Column with the duration of each lap (since the previous lap), colored from best to worst.",
                "显示每圈的用时（距上一圈），颜色从最佳到最差渐变。"),
            Info("colDelta", S.COL_DELTA,
                "Colonne de l'écart de durée avec le tour précédent, au dixième de seconde (+ plus lent, − plus rapide).",
                "Column with the duration difference from the previous lap, to the tenth of a second (+ slower, − faster).",
                "显示与上一圈的用时差，精确到十分之一秒（+ 更慢，− 更快）。"),
            Info("colPace", S.COL_PACE,
                "Colonne de l'allure de chaque tour, en min/km.\nNécessite le suivi avancé et une distance par tour supérieure à 0.",
                "Column with each lap's pace, in min/km.\nRequires advanced tracking and a distance per lap above 0.",
                "显示每圈配速，单位为 分/公里。\n需要启用高级跟踪，且每圈距离大于 0。"),
            Info("showAvg", S.AVG,
                "Affiche la moyenne des tours en tête de liste, à partir de deux tours.",
                "Shows the average lap time at the top of the list, from two laps on.",
                "从两圈开始，在列表顶部显示平均圈速。"),
            Info("qrVer", S.QR_VERSION,
                "Taille du code QR de la séance (version 5 à 25). Plus la version est haute, plus le code contient de tours, mais plus ses carrés sont petits et difficiles à lire.\nSi la séance est trop longue, plusieurs codes sont créés : on les fait défiler à gauche / droite.",
                "Size of the session's QR code (version 5 to 25). The higher the version, the more laps one code holds, but the smaller and harder to scan its squares are.\nIf the session is too long, several codes are made: swipe left / right between them.",
                "记录二维码的大小（版本 5 至 25）。版本越高，单个二维码容纳的圈数越多，但方块也越小、越难扫描。\n记录过长时会生成多个二维码，可左右滑动切换。"),
            Info("qrEc", S.QR_EC,
                "Niveau de correction d'erreur du code QR : L (7 %), M (15 %), Q (25 %) ou H (30 %).\nUn niveau élevé résiste mieux aux rayures et aux reflets, mais contient moins de tours.",
                "QR error-correction level: L (7 %), M (15 %), Q (25 %) or H (30 %).\nA higher level resists scratches and glare better but holds fewer laps.",
                "二维码纠错等级：L（7 %）、M（15 %）、Q（25 %）或 H（30 %）。\n等级越高越耐刮擦和反光，但容纳的圈数越少。"),
            Info("chrono", S.S_CHRONO,
                "Taille des chiffres du temps principal, en sp.\nAu-delà d'une heure, les chiffres sont automatiquement réduits d'environ 20 % pour tenir à l'écran.",
                "Size of the main time digits, in sp.\nPast one hour, the digits are automatically reduced by about 20 % to fit the screen.",
                "主时间数字的大小，单位 sp。\n超过一小时后，数字会自动缩小约 20 % 以适应屏幕。"),
            Info("btn", S.S_BTN,
                "Diamètre des cercles Start, Tour, Reset et Annuler, en dp.\nAvec le bouton Annuler, les cercles sont réduits de 17 %.",
                "Diameter of the Start, Lap, Reset and Undo circles, in dp.\nWith the Undo button, circles are reduced by 17 %.",
                "开始、计圈、重置和撤销圆形按钮的直径，单位 dp。\n启用撤销按钮时，按钮会缩小 17 %。"),
            Info("lap", S.S_LAPS,
                "Taille du texte de la liste des tours, en sp.\nLes colonnes s'adaptent automatiquement : aucun texte n'est coupé.",
                "Text size of the lap list, in sp.\nColumns adapt automatically: no text is cut off.",
                "圈次列表的文字大小，单位 sp。\n各列会自动适应，文字不会被截断。"),
            Info("gapTimeBtn", S.GAP_TIME_BTN,
                "Espace entre les chiffres du chrono et les cercles, en % de la hauteur de l'écran.\n0 % : le bas des chiffres touche le haut des cercles. Les valeurs négatives (jusqu'à −10 %) les font se chevaucher pour les rapprocher encore.",
                "Space between the timer digits and the circles, in % of the screen height.\n0 %: the bottom of the digits touches the top of the circles. Negative values (down to −10 %) make them overlap to bring them even closer.",
                "秒表数字与圆形按钮之间的间距，占屏幕高度的百分比。\n0 %：数字底部刚好碰到按钮顶部。负值（最低 −10 %）会让二者重叠，靠得更近。"),
            Info("btnGap", S.GAP_BTN,
                "Espace entre les cercles, en % de la hauteur de l'écran.",
                "Space between the circles, in % of the screen height.",
                "圆形按钮之间的间距，占屏幕高度的百分比。"),
            Info("gapBtnLap", S.GAP_BTN_LAP,
                "Espace entre les cercles et la liste des tours, en % de la hauteur de l'écran.",
                "Space between the circles and the lap list, in % of the screen height.",
                "圆形按钮与圈次列表之间的间距，占屏幕高度的百分比。"),
            Info("lineGap", S.GAP_LINES,
                "Espace entre deux lignes de tours, en % de la hauteur de l'écran.\nÀ 0 %, les lignes se touchent.",
                "Space between two lap lines, in % of the screen height.\nAt 0 %, lines touch each other.",
                "相邻两行圈次之间的间距，占屏幕高度的百分比。\n为 0 % 时各行紧挨。"),
            Info("topPct", S.TOP_PCT,
                "Part de l'écran réservée au haut (chrono et cercles), en %. Le reste est pour la liste des tours.\nÀ 100 %, la liste disparaît ; à 0 %, le chrono disparaît.",
                "Share of the screen given to the top (timer and circles), in %. The rest is for the lap list.\nAt 100 % the list disappears; at 0 % the timer disappears.",
                "屏幕上方（计时与按钮）所占比例，单位 %，其余用于圈次列表。\n100 % 时列表消失；0 % 时计时消失。"),
            Info("lapWidth", S.LAP_WIDTH,
                "Largeur disponible pour les lignes de tours, en % de la largeur de l'écran.\nSi les colonnes ont besoin de plus de place, la ligne s'élargit automatiquement.",
                "Width available for lap lines, in % of the screen width.\nIf columns need more room, the line widens automatically.",
                "圈次行可用的宽度，占屏幕宽度的百分比。\n若各列需要更多空间，行宽会自动加宽。"),
            Info("vibe", S.VIBE,
                "Intensité des vibrations (start, stop, tour, reset, objectifs). 0 % = aucune vibration.\nRelâcher le curseur fait vibrer la montre pour tester l'intensité.",
                "Vibration strength (start, stop, lap, reset, goals). 0 % = no vibration.\nReleasing the slider makes the watch vibrate so you can feel the strength.",
                "振动强度（开始、停止、计圈、重置、目标）。0 % = 不振动。\n松开滑块时手表会振动，方便感受强度。"),
            Info("autoStop", S.AUTO_STOP,
                "Arrête le chrono tout seul après cette durée, figé exactement à la limite, même si l'écran est éteint.\n« Désactivé » = pas de limite.\nUn appui long ouvre la plage min / max du curseur.",
                "Stops the timer by itself after this duration, frozen exactly at the limit, even with the screen off.\n« Off » = no limit.\nA long press opens the slider's min / max range.",
                "超过此时长后秒表自动停止，并精确定格在该时间，即使屏幕熄灭也有效。\n“关闭”表示无限制。\n长按可打开滑块的最小 / 最大范围。"),

            // ---------------- Suivi avancé
            Info("precision", S.TRACK_PRECISION,
                "Pas de réglage de la distance par tour : de 0,1 m à 1000 m.\nUn pas fin permet de régler une distance précise (une piste de 400 m, une longueur de 25 m…).",
                "Adjustment step of the distance per lap: from 0.1 m to 1000 m.\nA fine step lets you set an exact distance (a 400 m track, a 25 m pool length…).",
                "每圈距离的调节步长：0.1 米至 1000 米。\n较小的步长便于设置精确距离（400 米跑道、25 米泳池等）。"),
            Info("distance", S.TRACK_DIST,
                "Distance parcourue à chaque tour. Elle sert à calculer l'allure (min/km) de chaque tour.\n0 = pas d'allure. Il faut aussi activer la colonne « Allure ».",
                "Distance covered in each lap. It is used to compute each lap's pace (min/km).\n0 = no pace. The « Pace » column must also be enabled.",
                "每圈的距离，用于计算每圈的配速（分/公里）。\n0 表示不计算配速。还需要启用“配速”列。"),
            Info("exTime", S.EX_TIME,
                "Durée d'un exercice (une répétition). À la fin, la montre vibre. 0 = pas d'objectif.\nLe cercle se remplit alors pendant chaque segment d'exercice ou de repos.",
                "Duration of one exercise (one repetition). The watch vibrates at the end. 0 = no goal.\nThe ring then fills during each exercise or rest segment.",
                "单次运动（一次重复）的时长，结束时手表会振动。0 = 无目标。\n圆环会在每个运动或休息阶段内逐渐填满。"),
            Info("nbRep", S.EX_REPS,
                "Nombre de répétitions d'exercice avant le repos. Une série = ce nombre de tours.\nAvec les triangles ▲▼ activés, chaque tour est comparé au tour de même rang dans la série précédente.",
                "Number of exercise repetitions before the rest. One series = that many laps.\nWith the ▲▼ triangles enabled, each lap is compared with the lap of the same rank in the previous series.",
                "休息前的运动重复次数。一组 = 这么多圈。\n启用 ▲▼ 三角后，每一圈会与上一组中相同序号的一圈比较。"),
            Info("restTime", S.REST_TIME,
                "Durée du repos après les répétitions, avant de recommencer une série. 0 = pas de repos.\nLa montre vibre au début puis à la fin du repos.",
                "Duration of the rest after the repetitions, before a new series starts. 0 = no rest.\nThe watch vibrates at the start and at the end of the rest.",
                "重复结束后、开始新一组之前的休息时长。0 = 不休息。\n休息开始和结束时手表都会振动。"),
            Info("trackVibe", S.TRACK_VIBE,
                "Si activé, la montre vibre (comme pour un tour) à chaque objectif atteint : fin d'un exercice, début du repos et fin du repos.\nSi désactivé, seul le cercle indique la progression.",
                "When on, the watch vibrates (like a lap) at each goal reached: end of an exercise, start of the rest and end of the rest.\nWhen off, only the ring shows progress.",
                "开启后，每达到一个目标（运动结束、休息开始、休息结束），手表都会像计圈一样振动。\n关闭后，仅通过圆环显示进度。")
        )
        val byKey: Map<String, Info> = all.associateBy { it.key }
    }
}

/** Aide complète : (titre, texte). Les lignes du texte sont séparées par « \n ». */
val HELP_SECTIONS: List<Pair<T3, T3>> = listOf(
    T3("Démarrer et compter", "Start and count", "开始与计时") to T3(
        "Start lance le chrono, Stop l'arrête. En marche, le cercle de gauche devient Tour : chaque appui enregistre un tour.\nLe bouton physique du bas fait pareil (Start, puis Tour). Écran éteint ou en veille, le premier appui sert seulement à réveiller.\nAnnuler (option) retire le dernier tour.",
        "Start launches the timer, Stop halts it. While running, the left circle becomes Lap: each press records a lap.\nThe bottom physical button does the same (Start, then Lap). With the screen off or dimmed, the first press only wakes it.\nUndo (option) removes the last lap.",
        "点“开始”启动秒表，点“停止”暂停。运行时左侧圆形按钮变为“计圈”，每按一次记录一圈。\n底部实体按键功能相同（先开始，再计圈）。屏幕熄灭或待机时，第一次按键只用于唤醒。\n“撤销”（可选）会删除最近一圈。"),
    T3("Remettre à zéro", "Reset", "重置") to T3(
        "Quand le chrono est arrêté, le cercle de gauche devient Reset. Il faut le maintenir (temps réglable dans les réglages) : un cercle se remplit autour de l'écran puis la montre vibre.\nLa séance est alors ajoutée à l'historique.",
        "When the timer is stopped, the left circle becomes Reset. You must hold it (time set in settings): a ring fills around the screen, then the watch vibrates.\nThe session is then added to the history.",
        "秒表停止后，左侧圆形按钮变为“重置”。需要按住（时间可在设置中调整）：屏幕周围的圆环填满后手表振动。\n该次记录会加入历史。"),
    T3("Appuis longs", "Long presses", "长按") to T3(
        "Les actions sensibles se valident en maintenant le doigt : Reset, effacer l'historique, supprimer une séance, cadenas, remise à zéro de la mise en page ou d'une plage.\nLe temps de maintien se règle dans les réglages essentiels.\nSur n'importe quel réglage, un appui long affiche son explication.",
        "Sensitive actions are confirmed by holding your finger: Reset, clear history, delete a session, padlock, default layout or default range.\nThe hold time is set in the essential settings.\nOn any setting, a long press shows its explanation.",
        "敏感操作需要按住确认：重置、清除历史、删除记录、解锁、恢复默认布局或默认范围。\n按住时间可在基本设置中调整。\n在任何设置项上长按都会显示其说明。"),
    T3("Liste des tours", "Lap list", "圈次列表") to T3(
        "Les tours s'affichent du plus récent au plus ancien. Faites-les défiler avec la bague rotative (une ligne par cran) ou au doigt.\nChaque ligne montre le numéro, le total, la durée du tour, l'allure (suivi avancé) et l'écart avec le tour précédent. Les colonnes se choisissent dans la Personnalisation.\nLa durée est colorée du meilleur au pire tour ; les triangles ▲▼ (option) comparent chaque tour à sa référence.",
        "Laps are listed from newest to oldest. Scroll with the rotary bezel (one line per click) or with your finger.\nEach line shows the number, total, lap time, pace (advanced tracking) and the difference from the previous lap. Columns are chosen in Customize.\nThe time is colored from best to worst lap; the ▲▼ triangles (option) compare each lap with its reference.",
        "圈次按从新到旧排列。可用旋转表圈（每格一行）或手指滚动。\n每行显示序号、总计、单圈用时、配速（高级跟踪）以及与上一圈的差值。列可在“个性化”中选择。\n用时颜色从最佳到最差渐变；▲▼ 三角（可选）将每圈与其参照比较。"),
    T3("Verrou tactile", "Touch lock", "触屏锁定") to T3(
        "Avec l'option activée, l'écran se verrouille au lancement du chrono pour éviter les appuis involontaires. Le bouton physique reste actif.\nMaintenez le cadenas en haut de l'écran pour déverrouiller, ou réglez un déverrouillage automatique.",
        "With the option on, the screen locks when the timer starts to avoid accidental touches. The physical button stays active.\nHold the padlock at the top of the screen to unlock, or set an automatic unlock.",
        "开启后，启动秒表时屏幕会自动锁定，避免误触，实体按键仍可使用。\n长按屏幕顶部的锁图标即可解锁，也可设置自动解锁。"),
    T3("Suivi avancé", "Advanced tracking", "高级跟踪") to T3(
        "Distance par tour : donne l'allure (min/km) de chaque tour.\nObjectifs : un temps d'exercice, un nombre de répétitions et un temps de repos. Le cercle suit le segment en cours et la montre vibre à chaque objectif atteint (désactivable).\nCes réglages restent accessibles pendant l'activité par un appui long sur l'icône de suivi.",
        "Distance per lap: gives each lap's pace (min/km).\nGoals: an exercise time, a number of repetitions and a rest time. The ring follows the current segment and the watch vibrates at each goal reached (can be turned off).\nThese settings stay reachable during an activity with a long press on the tracking icon.",
        "每圈距离：计算每圈的配速（分/公里）。\n目标：运动时间、重复次数和休息时间。圆环对应当前阶段，每达到一个目标手表就会振动（可关闭）。\n活动期间长按跟踪图标即可进入这些设置。"),
    T3("Historique", "History", "历史记录") to T3(
        "Chaque Reset enregistre la séance (50 au maximum, nom = date et heure).\nGlissez une séance vers la droite pour l'ouvrir : statistiques (meilleur, pire, moyenne, médiane, écart-type, régularité), liste des tours et codes QR.\nMaintenez une séance pour la supprimer, ou le bouton du bas de la liste pour tout effacer.",
        "Each Reset saves the session (50 at most, named by date and time).\nSwipe a session to the right to open it: statistics (best, worst, average, median, standard deviation, consistency), lap list and QR codes.\nHold a session to delete it, or the button at the bottom of the list to clear everything.",
        "每次重置都会保存该次记录（最多 50 条，以日期和时间命名）。\n向右滑动某条记录即可打开：统计（最佳、最差、平均、中位数、标准差、稳定度）、圈次列表和二维码。\n长按某条记录可删除，长按列表底部按钮可全部清除。"),
    T3("Codes QR", "QR codes", "二维码") to T3(
        "Dans une séance, le bouton QR affiche les temps de tour sous forme de codes QR (fond blanc, luminosité maximale). Scannez-les avec un téléphone pour récupérer les données.\nSi la séance est longue, plusieurs codes se suivent : faites défiler à gauche ou à droite.\nLa version et la correction d'erreur se règlent dans la Personnalisation.",
        "In a session, the QR button shows the lap times as QR codes (white background, maximum brightness). Scan them with a phone to get the data.\nIf the session is long, several codes follow one another: swipe left or right.\nVersion and error correction are set in Customize.",
        "在记录中点二维码按钮，圈次用时会以二维码显示（白底、最高亮度）。用手机扫描即可获取数据。\n记录较长时会有多个二维码，可左右滑动切换。\n版本和纠错等级可在“个性化”中设置。"),
    T3("Réglages et curseurs", "Settings and sliders", "设置与滑块") to T3(
        "Un appui sur un interrupteur le bascule. Un curseur se règle en glissant ou en touchant la barre.\nAppui long sur un interrupteur : explication du réglage. Appui long sur un curseur : explication, puis plage min / max (100 pas entre les deux) et retour à la plage d'origine.\nLes durées s'affichent en secondes, minutes ou heures.",
        "A tap on a switch flips it. A slider is set by dragging or touching the bar.\nLong press on a switch: explanation of the setting. Long press on a slider: explanation, then min / max range (100 steps between them) and reset to the original range.\nDurations are shown in seconds, minutes or hours.",
        "点按开关即可切换。滑块可拖动或点按进度条来调节。\n长按开关：显示该设置的说明。长按滑块：显示说明，并可设置最小 / 最大范围（两者之间分 100 步）或恢复原始范围。\n时长以秒、分钟或小时显示。"),
    T3("Mode éco", "Eco mode", "省电模式") to T3(
        "Noir et blanc, une mise à jour par seconde, sans dixièmes, luminosité réglable : l'écran consomme beaucoup moins.\nLes tours sont écrits au fil de l'eau dans un fichier, ce qui limite les accès mémoire.",
        "Black and white, one refresh per second, no tenths, adjustable brightness: the screen uses far less power.\nLaps are appended to a file as you go, which limits storage writes.",
        "黑白显示，每秒刷新一次，不显示十分之一秒，亮度可调：屏幕耗电大幅降低。\n圈次会随时追加写入文件，减少存储写入。"),
    T3("Affichage permanent et mode clair", "Always-on and light mode", "常亮显示与浅色模式") to T3(
        "Affichage permanent : l'écran reste allumé tant que le chrono tourne, malgré la veille du système. Après le délai réglé sans toucher la montre, il passe en veille douce (noir, chiffres gris, luminosité minimale). Un appui ou le bouton du bas le réveille.\nMode clair : fond blanc, texte noir.\nLes deux demandent confirmation : ils risquent de marquer l'écran AMOLED et usent la batterie.",
        "Always-on: the screen stays on while the timer runs, despite the system's sleep. After the set delay without touching the watch, it goes to a soft dim state (black, gray digits, minimum brightness). A touch or the bottom button wakes it.\nLight mode: white background, black text.\nBoth ask for confirmation: they risk burning the AMOLED screen and drain the battery.",
        "常亮显示：秒表运行期间，屏幕不受系统息屏影响，保持常亮。在设定时间内未触碰手表后，进入柔和待机（黑底、灰字、最低亮度）。触摸屏幕或按底部按键即可唤醒。\n浅色模式：白底黑字。\n两者都需要确认：可能造成 AMOLED 烧屏并加快耗电。"),
    T3("Fermeture de l'appli", "Closing the app", "关闭应用") to T3(
        "Quitter l'appli (retour au cadran) ne coupe pas le chrono : il continue, visible sur le tile, la complication et la pastille « chrono en cours ».\nSi l'appli est fermée (retirée des applis récentes) ou si vous faites « Forcer l'arrêt », le chrono est arrêté et remis à zéro dès que l'appli se relance : la séance est enregistrée dans l'historique.\nUn redémarrage de la montre ne remet pas le chrono à zéro.",
        "Leaving the app (back to the watch face) does not stop the timer: it keeps running, visible on the tile, the complication and the « timer running » chip.\nIf the app is closed (removed from recent apps) or you use « Force stop », the timer is stopped and reset as soon as the app starts again: the session is saved in the history.\nRestarting the watch does not reset the timer.",
        "退出应用（返回表盘）不会停止秒表，它会继续运行，并显示在磁贴、表盘复杂功能和“秒表运行中”提示上。\n若应用被关闭（从最近应用中移除）或执行“强制停止”，应用再次启动时会立即停止并重置秒表，该次记录会保存到历史中。\n手表重启不会重置秒表。"),
    T3("Tile, cadran et pastille", "Tile, watch face and chip", "磁贴、表盘与提示") to T3(
        "Le tile permet de lancer, de prendre un tour et d'arrêter sans ouvrir l'appli. La complication affiche le chrono sur le cadran, et la pastille « chrono en cours » propose Stop + Reset.\nLeur pictogramme suit le logo choisi.",
        "The tile lets you start, lap and stop without opening the app. The complication shows the timer on the watch face, and the « timer running » chip offers Stop + Reset.\nTheir pictogram follows the chosen logo.",
        "磁贴可以在不打开应用的情况下开始、计圈和停止。表盘复杂功能在表盘上显示秒表，“秒表运行中”提示提供“停止并重置”。\n它们的图标与所选图标一致。"),
    T3("En cas de problème", "Troubleshooting", "遇到问题") to T3(
        "Plus de réglages accessibles pendant l'activité : remettez le chrono à zéro, ou réactivez « Réglages en activité ».\nL'écran tactile ne répond plus : le verrou est actif, maintenez le cadenas ou utilisez le bouton du bas.\nPour repartir de zéro, effacez les données de l'appli dans les paramètres Android.",
        "No settings reachable during an activity: reset the timer, or turn « Settings while running » back on.\nThe touchscreen does not respond: the lock is on, hold the padlock or use the bottom button.\nTo start fresh, clear the app's data in Android settings.",
        "活动期间无法进入设置：请重置秒表，或重新开启“运行中显示设置”。\n触摸屏没有反应：锁定已开启，请长按锁图标或使用底部按键。\n若要恢复初始状态，请在 Android 设置中清除应用数据。")
)
